xrp-kernel: rename 'halt' to avoid name clash
Fix the following build error when building with kernel v5.10:

xrp-kernel/xrp_hw_simple.c:130:13: error: conflicting types for ‘halt’
 static void halt(void *hw_arg)
             ^~~~
In file included from linux-5.10/include/linux/irqflags.h:16,
                 from linux-5.10/arch/x86/include/asm/special_insns.h:10,
                 from linux-5.10/arch/x86/include/asm/processor.h:25,
                 from linux-5.10/arch/x86/include/asm/cpufeature.h:5,
                 from linux-5.10/arch/x86/include/asm/thread_info.h:53,
                 from linux-5.10/include/linux/thread_info.h:38,
                 from linux-5.10/arch/x86/include/asm/preempt.h:7,
                 from linux-5.10/include/linux/preempt.h:78,
                 from linux-5.10/include/linux/percpu.h:6,
                 from linux-5.10/include/linux/context_tracking_state.h:5,
                 from linux-5.10/include/linux/hardirq.h:5,
                 from linux-5.10/include/linux/interrupt.h:11,
                 from xrp-kernel/xrp_hw_simple.c:30:
linux-5.10/arch/x86/include/asm/irqflags.h:110:30: note: previous definition of ‘halt’ was here
 static inline __cpuidle void halt(void)

Signed-off-by: Max Filippov <jcmvbkbc@gmail.com>